# ~/.config/alacritty/alacritty.yml
# Pavel Novák


window:
    padding:
        x: 10
        y: 10


key_bindings:
 - { key: Back, mods: Control, chars: "\x17" }  # Delete word on left - Ctrl + W
 - { key: Delete, mods: Control, chars: "\x1b\x64" } # Delete word on right - Alt + D:
 - { key: Minus, mods: Control, action: DecreaseFontSize }
 - { key: Plus, mods: Control, action: IncreaseFontSize }
 - { key: Key0, mods: Control, action: ResetFontSize }


# selection:
    # sematic_escape_chars: '",.:|()[]{}'  What does this do?


background_opacity: 0.75


font:
    normal:
        family: "RobotoMono Nerd Font Mono"
        style: Regular
    bold:
        family: "RobotoMono Nerd Font Mono"
        style: Bold
    italics:
        family: "RobotoMono Nerd Font Mono"
        style: Regular Italic
    bold_italic:
        family: "RobotoMono Nerd Font Mono"
        style: Bold Italic

    size: 8
    offset:
        x: -1
        y: 0
    hinting: true
    antialias: true 
    thin_strokes: true


cursor:
    style:
        shape: beam


# Colors (IR Black)
colors:
    # Default colors
    primary:
        background: '#000000'
        foreground: '#ffffff'

    cursor:
        text: '#ffffff'
        cursor: '#ffffff'

    # Normal colors
    normal:
        black:   '#4e4e4e'
        red:     '#ff6c60'
        green:   '#a8ff60'
        yellow:  '#ffffb6'
        blue:    '#96cbfe'
        magenta: '#ff73fd'
        cyan:    '#c6c5fe'
        white:   '#eeeeee'

    # Bright colors
    bright:
        black:   '#7c7c7c'
        red:     '#ffb6b0'
        green:   '#ceffab'
        yellow:  '#ffffcb'
        blue:    '#b5dcfe'
        magenta: '#ff9cfe'
        cyan:    '#dfdff0'
        white:   '#ffffff'

