theme = "bw_diving_dracula"

[editor]
color-modes = true
scroll-lines = 3
shell = ["zsh", "-c"]
line-number = "relative"
auto-completion = true
auto-format = true
auto-save = false
idle-timeout = 0
rulers = [80, 100, 120]
bufferline = "always"
cursorline = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.statusline]
left   = ["mode", "position"]
center = ["file-type", "separator", "file-name", "separator", "total-line-numbers"]
right  = ["diagnostics", "workspace-diagnostics"]

[keys.normal]
backspace = "command_mode"
# C-b = ":sh cargo run"

# Handy when using czech keyboard:
"ů"   = "collapse_selection"
"A-ů" = "flip_selections"

[keys.insert]
# move line up
"A-up"     = ["extend_line","yank","move_line_up","open_above","replace_with_yanked","move_line_down", "move_line_down", "extend_line", "delete_selection", "move_line_up", "move_line_up"]
# move line down
"A-down"   = ["extend_line","delete_selection", "paste_after", "move_line_down"]
# duplicate line up
"S-A-up"   = ["extend_line","yank","open_above","normal_mode","replace_with_yanked", "insert_mode"]
# duplicate line down
"S-A-down" = ["extend_line","yank","move_line_down","open_above","normal_mode","replace_with_yanked", "insert_mode"]