theme = "bw_diving_dracula"

[editor]
color-modes = true
scroll-lines = 3
shell = ["zsh", "-c"]
line-number = "relative"
auto-completion = true
auto-format = true
auto-save = false
idle-timeout = 0
completion-trigger-len = 1
rulers = [80, 100, 120]
bufferline = "always"
cursorline = true
#editor = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left   = ["mode", "position"]
center = ["file-type", "separator", "file-name", "separator", "total-line-numbers"]
right  = ["diagnostics", "workspace-diagnostics", "spinner"]

[keys.normal]
# Backspace goes to command mode
backspace = "command_mode"
# Select word (inner) same as "miw" or "bw" 
"A-w" = ["move_prev_word_start", "move_next_word_start"]
# Handy when using czech keyboard:
"ů"   = "collapse_selection"
"A-ů" = "flip_selections"  # Doesn't work ??

[keys.insert]
# move line up
"A-up"     = ["extend_line","yank","move_line_up","open_above","replace_with_yanked","move_line_down", "move_line_down", "extend_line", "delete_selection", "move_line_up", "move_line_up"]
# move line down
"A-down"   = ["extend_line","delete_selection", "paste_after", "move_line_down"]
# duplicate line up
"S-A-up"   = ["extend_line","yank","open_above","normal_mode","replace_with_yanked", "insert_mode"]
# duplicate line down
"S-A-down" = ["extend_line","yank","move_line_down","open_above","normal_mode","replace_with_yanked", "insert_mode"]