theme = "bw_diving_monokai_aqua"

[editor]
color-modes = true
scroll-lines = 3
shell = ["zsh", "-c"]
line-number = "relative"
auto-completion = true
auto-format = true
auto-save = false
idle-timeout = 0
completion-trigger-len = 1
rulers = [80, 100, 120]
bufferline = "always"
cursorline = true
soft-wrap.enable = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left   = ["mode", "position"]
center = ["file-type", "separator", "file-name", "separator", "total-line-numbers"]
right  = ["diagnostics", "workspace-diagnostics", "spinner"]

[keys.normal]
# Extend line above
# S-m = ["select_mode", "extend_line_below", "move_line_up", "move_line_up", "normal_mode" ]
# # HJKL to IJKL
# i   = "move_line_up"
# j   = "move_char_left"
# k   = "move_line_down"
# l   = "move_char_right"
# ret = "insert_mode"
# Backspace goes to command mode
backspace = "command_mode"
# Select word (inner) same as "miw" or "bw" 
"A-w" = ["move_prev_word_start", "move_next_word_start"]
# Handy when using czech keyboard:
"ů"   = "collapse_selection"
"A-ů" = "flip_selections"  # Doesn't work ??
# Duplicate line up
"C-A-j" = ["extend_line_below","yank","open_below","normal_mode", "replace_with_yanked", "collapse_selection"]
# Duplicate line down
"C-A-k" = ["extend_line_below","yank","open_above","normal_mode", "replace_with_yanked", "collapse_selection"]
# Move line up
"A-k" = [
  "move_line_up",
  "extend_line_below",
  "extend_line_below",
  "split_selection_on_newline",
  "rotate_selection_contents_forward",
  "collapse_selection",
  "keep_primary_selection"
]

# Move line down
"A-j" = [
  "extend_line_below",
  "extend_line_below",
  "split_selection_on_newline",
  "rotate_selection_contents_forward",
  "collapse_selection",
  "remove_primary_selection"
]

