default_window_width = 600
max_content_height = 400
name_match_highlight_color = "white"
decorate_window = false
close_window_on_losing_focus = true
query_placeholder = "Search"
icon_size = 20
toggle_key = "<Super>space"
min_score = 2

[plugins]
cmd = { path = "~/.config/findex/plugins/libcmd.so", config = {} }

