efault_window_width = 600
min_content_height = 0
max_content_height = 400
name_match_highlight_color = "white"
decorate_window = false
close_window_on_losing_focus = true
query_placeholder = "Search for applications"
icon_size = 20
toggle_key = "<Alt>space"
min_score = 5
