#!/bin/bash

#  ██████╗ ██╗    ██╗    ██████╗ ██╗██╗   ██╗██╗███╗   ██╗ ██████╗ 
#  ██╔══██╗██║    ██║    ██╔══██╗██║██║   ██║██║████╗  ██║██╔════╝ 
#  ██████╔╝██║ █╗ ██║    ██║  ██║██║██║   ██║██║██╔██╗ ██║██║  ███╗
#  ██╔══██╗██║███╗██║    ██║  ██║██║╚██╗ ██╔╝██║██║╚██╗██║██║   ██║
#  ██████╔╝╚███╔███╔╝    ██████╔╝██║ ╚████╔╝ ██║██║ ╚████║╚██████╔╝
#  ╚═════╝  ╚══╝╚══╝     ╚═════╝ ╚═╝  ╚═══╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝ 
# Author: Pavel Novák
# Github: https://github.com/Pavel-N
# Description: My BSWPM setup.

# Set the mouse pointer
xsetroot -cursor_name left_ptr

# Set the wallpaper
feh --bg-fill ~/Pictures/Wallpapers/diving_taliacohen.jpg

# Start xchkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Start Picom
killall picom
while pgrep -x picom >/dev/null; do sleep 1; done
picom --experimental-backend -b

# Start Polybar
~/.config/polybar/launch_polybar

# ===== BSPWM Config =====
# Monitor(s)
is_external=$(xrandr --query | grep 'HDMI2')
if [[ $is_external != *disconnected* ]]  # Detect second monitor(s)
then
  ~/.config/.screenlayout/both.sh
  bspc monitor eDP1 -d 6 7 8 9 0
  bspc monitor HDMI2 -d 1 2 3 4 5
else
  ~/.config/.screenlayout/laptop_only.sh
  bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9            
fi
bspc config remove_unplugged_monitors true
# Basics
bspc config top_padding           40         # Top padding for polybar
# Border
bspc config border_width          2          # Border width
bspc config normal_border_color   "#454545"  # Border color on unactive windows
bspc config focused_border_color  "#B5B5B5"  # Border color of focused window
# Windows
bspc config window_gap            15         # Gap bewteen windows
bspc config split_ratio           0.50       # Split ratio when new window opens
# Preselect
bspc config presel_feedback true             # Preselect feedback enabled
bspc config presel_feedback_color "#202020"  # Color of the preselect feedback rectangle
# Monocle 
bspc config borderless_monocle    false      # Monocle is not borderless
bspc config gapless_monocle       false      # Monocle is not gappless

