#!/bin/bash
# This script will start/restart Polybar

# Kill all running Polybar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Start new polybar instance on every connected monitor
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --config=~/.config/polybar/left.ini --reload left &
    polybar --config=~/.config/polybar/center.ini --reload center &
    polybar --config=~/.config/polybar/right.ini --reload right &
  done
fi

